[
    {
      "id": 1,
      "category": "Art & Design",
      "title": "Mastering Digital Illustration",
      "image": "../src/assets/courses/digital-illustration.jpg",
      "lessons": 12,
      "duration": "5 hours",
      "level": "Beginner",
      "price": 25.99,
      "discountPrice": 19.99,
      "featured": true,
      "discount": 23,
      "popular": true
    },
    {
      "id": 2,
      "category": "Art & Design",
      "title": "Graphic Design Fundamentals",
      "image": "../src/assets/courses/graphic-design.jpg",
      "lessons": 14,
      "duration": "6 hours",
      "level": "Intermediate",
      "price": 29.99,
      "discountPrice": 24.99,
      "featured": false,
      "discount": 17,
      "popular": false
    },
    {
      "id": 3,
      "category": "Art & Design",
      "title": "Adobe Photoshop Masterclass",
      "image": "../src/assets/courses/photoshop.jpg",
      "lessons": 18,
      "duration": "7.5 hours",
      "level": "Advanced",
      "price": 39.99,
      "discountPrice": 29.99,
      "featured": true,
      "discount": 25,
      "popular": true
    },
    {
      "id": 4,
      "category": "Development",
      "title": "Full-Stack Web Development",
      "image": "../src/assets/courses/web-development.jpg",
      "lessons": 20,
      "duration": "10 hours",
      "level": "Expert",
      "price": 49.99,
      "discountPrice": 39.99,
      "featured": true,
      "discount": 20,
      "popular": true
    },
    {
      "id": 5,
      "category": "Development",
      "title": "ReactJS for Beginners",
      "image": "../src/assets/courses/react.jpg",
      "lessons": 18,
      "duration": "7 hours",
      "level": "Intermediate",
      "price": 39.99,
      "discountPrice": 29.99,
      "featured": false,
      "discount": 25,
      "popular": false
    },
    {
      "id": 6,
      "category": "Development",
      "title": "Node.js & Express Mastery",
      "image": "../src/assets/courses/nodejs.jpg",
      "lessons": 22,
      "duration": "8 hours",
      "level": "Advanced",
      "price": 45.99,
      "discountPrice": 34.99,
      "featured": true,
      "discount": 24,
      "popular": true
    },
    {
      "id": 7,
      "category": "Lifestyle",
      "title": "Minimalist Living: Declutter Your Life",
      "image": "../src/assets/courses/lifestyle.jpg",
      "lessons": 8,
      "duration": "3.5 hours",
      "level": "Intermediate",
      "price": 19.99,
      "discountPrice": 14.99,
      "featured": false,
      "discount": 25,
      "popular": false
    },
    {
      "id": 8,
      "category": "Lifestyle",
      "title": "Healthy Eating Habits",
      "image": "../src/assets/courses/healthy-eating.jpg",
      "lessons": 10,
      "duration": "4 hours",
      "level": "Beginner",
      "price": 24.99,
      "discountPrice": 19.99,
      "featured": true,
      "discount": 20,
      "popular": true
    },
    {
      "id": 9,
      "category": "Lifestyle",
      "title": "Stress Management Techniques",
      "image": "../src/assets/courses/stress-management.jpg",
      "lessons": 12,
      "duration": "5 hours",
      "level": "Intermediate",
      "price": 29.99,
      "discountPrice": 24.99,
      "featured": false,
      "discount": 17,
      "popular": false
    }
  ]